Лабораторная #1
slmtnm/graphics-labs pull request #1
Opened 2022-02-14 22:50 UTC by slmtnm

2022-02-15 09:54 UTC, anthark commented
У вас остались warnings от DirectX Debug Layer при создании swap chain и при выходе из-за подвисших объектов. 
Исполняемый файл не запускается сам по себе, без Visual Studio. 
Используйте, пожалуйста, VS 2019

2022-02-15 09:55 UTC, anthark commented
_Некоторые комментарии я выделил курсивом. Они необязательны для исправления, но, на мой взгляд, содержат полезные советы =)_

2022-02-15 09:56 UTC, anthark requested changes

2022-02-15 09:56 UTC, anthark commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
Каждый вызов QueryInterface для COM объекта, если он - вызов - был успешным, увеличивает счетчик ссылок объекта на 1. То есть, нужен соответствующий вызов Release(), который логично вызвать у того интерфейса, который вы получили в этом вызове QueryInterface()

2022-02-15 09:56 UTC, anthark commented on graphics.cpp
> +    hr = device->CreateVertexShader(pVSBlob->GetBufferPointer(), pVSBlob->GetBufferSize(), nullptr, &vertexShader);
Каждый интерфейс, наследованный от IUnknown содержит счетчик ссылок, а значит каждому нужно вызвать Release() перед выходом. Например, этот шейдер в итоге подвис.

2022-02-15 09:56 UTC, anthark commented on graphics.cpp
> +    if (FAILED(hr))
_М-м-м... Формально проверка есть, но нет никакой видимой для пользователя (и для вызывающего initGeometry() кода тоже, кстати) реакции. Если создание вершинного шейдера не прошло здесь, то мы выйдем с void, потом вызовем render() и получим краш в другом месте, не там, где ошибка._

2022-02-15 09:56 UTC, anthark commented on graphics.cpp
> +    if (device1)
_device1 получен через QueryInterface() от device, то есть они указывают на один и тот же объект. В итоге, для device1 Release() с проверкой смысла не имеет, поскольку там даже в хорошей ситуации счетчик всегда будет больше 1 (device и d3dDebug ссылаются). Плюс проверка device проверит тот же самый объект._

2022-02-15 09:56 UTC, anthark commented on graphics.cpp
> +void Graphics::releaseWithCheck(IUnknown *object) {
_Такая сигнатура оставляет потенциальную возможность вызвать функцию для объекта, для которого она не предназначена (шейдера, например), которой в будущем (если мы говорим о длительной разработке большой командой) обязательно кто-нибудь воспользуется =) И будет краш, поскольку d3dDebug не проверяется на != nullptr._ 

_Посмотрите, пожалуйста, комментарий про удаление device1 и обратите внимание, что ID3D11Device1 наследуется от ID3D11Device_

2022-02-17 22:29 UTC, kystyn commented
> У вас остались warnings от DirectX Debug Layer при создании swap chain и при выходе из-за подвисших объектов. Исполняемый файл не запускается сам по себе, без Visual Studio. Используйте, пожалуйста, VS 2019

На данный момент исполняемый файл успешно запускается из проводника.
Насколько критично использовать именно VS2019, а не VS2022? На что это влияет?
Live Object-ы мы победили
![image](https://user-images.githubusercontent.com/48070175/154581653-5129d358-0d3a-4097-bb9d-ed966afcd97c.png)

2022-02-17 23:45 UTC, kystyn commented on graphics.cpp
> +    if (device1)
Спасибо! Поправили

2022-02-17 23:46 UTC, kystyn commented on graphics.cpp
> +void Graphics::releaseWithCheck(IUnknown *object) {
Спасибо, поправили

2022-02-17 23:47 UTC, kystyn commented on graphics.cpp
> +    if (FAILED(hr))
В следующем задании подумаем над тем, какую сделать реакцию

2022-02-17 23:48 UTC, kystyn commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
Вызываем Release у  annotation, но у него единственного 2 ссылки

2022-02-17 23:48 UTC, kystyn commented on graphics.cpp
> +    hr = device->CreateVertexShader(pVSBlob->GetBufferPointer(), pVSBlob->GetBufferSize(), nullptr, &vertexShader);
Спасибо, так и сделали

2022-02-18 00:12 UTC, kystyn commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
Поэкспериментировав с вызовами Release-а у разных объектов, у меня создалось впечатление, что число  ссылок на полученный через QueryInterface объект изначально равно количеству ссылок на его родителя, и впоследствии увеличивается, если число ссылок на родителя увеличивает посредством появления других наследников. Почему я так решил?
1. context1->Release() возвращает 1 (т. е. до релиза было 2 = 1 на context + 1 на context1)
2. init context; init annotations(context); refs = annotations->Release(); init context1. Release возвращает 1 (т. е. до релиза было 2 = 1 на context + 1 на annotation)
3. init context; init context1; init annotations(context1); refs = annotations->Release(). annotatios->Release(), возвращает 2 (т. е. до релиза было 3 = 1 на context + 1 на context1 + 1 на annotation)
4. init context; init annotations(context); init context1; refs = annotations->Release() возвращает 2 (т. е. до релиза было 3 = 1 на context + 1 на context1 + 1 на annotation)

Если всё, что я написал, не бред, то тогда проверка живых объектов должна производиться всё же более сложным образом, с учётом описанной особенности. Прав ли я?

2022-02-18 09:40 UTC, anthark commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
Не бред, все почти так и есть. Только терминология немного неправильная: QueryInterface не создает новые объекты - он приводит указатель на объект к запрошенному типу и, если получается, увеличивает количество ссылок на объект. Короче говоря, это аналог dynamic_cast, только со счетчиком ссылок. То есть в вашем примере, в пункте три, например, есть только один объект - контекст. При этом context, context1 и annotations - это три указателя на него, как на три интерфейса, каждый из которых в нем реализован. 

Это легко заметить, если сравнить значение адреса, которое хранится в context и context1 - оно одинаковое =) Для annotations отличается - это, видимо, из-за множественного наследования в реализации контекста. 

В общем, в вашем коде в cleanup() должно быть вот так для annotations: 

`need_rldo |= releaseWithCheck(annotation, 2);`

2022-02-18 09:43 UTC, slmtnm commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
Стало понятнее, спасибо!

2022-02-18 09:46 UTC, anthark commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
Но! Каждый объект, создаваемый через ID3D11Device (шейдеры, текстуры, буферы, все, что угодно) хранит указатель на этот device. И увеличивает счетчик ссылок на него. 

Поэтому, если мы вызвали device->Release() и оно вернуло 0, то это означает, что все ранее созданные через него объекты к этому времени удалены и на него не ссылаются, а значит, все чисто. 

Мы проверяем на 1, а не на 0, потому как непосредственно перед этим вызовом запрашиваем у него еще один интерфейс для ID3D11Debug. И в итоге, именно он оказывается последним указателем, после релиза которого, сам device тоже удаляется.

2022-02-18 09:46 UTC, anthark commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
В общем, проверку нужно делать только для device =)

2022-02-18 09:50 UTC, slmtnm commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
выходит две ссылки на "annotation", это указатель в переменной annotation + указатель в переменной context 
а так как context релизится позже annotation, сравниваем с 2
@kystyn

2022-02-18 09:51 UTC, anthark commented
> > У вас остались warnings от DirectX Debug Layer при создании swap chain и при выходе из-за подвисших объектов. Исполняемый файл не запускается сам по себе, без Visual Studio. Используйте, пожалуйста, VS 2019
> 
> На данный момент исполняемый файл успешно запускается из проводника. Насколько критично использовать именно VS2019, а не VS2022? На что это влияет? Live Object-ы мы победили все, за исключением annotation-а. Почему-то на него 2 ссылки

Можно VS2022, но тогда в настройках проекта, смените, пожалуйста, platform toolset на v142. Поскольку в противном случае мне придется все время менять настройки проекта, чтобы он собирался. А установить VS2022 или platform toolset v143, я на рабочем компе не могу =(

2022-02-18 09:55 UTC, anthark commented
> > У вас остались warnings от DirectX Debug Layer при создании swap chain и при выходе из-за подвисших объектов. Исполняемый файл не запускается сам по себе, без Visual Studio. Используйте, пожалуйста, VS 2019
> 
> На данный момент исполняемый файл успешно запускается из проводника. Насколько критично использовать именно VS2019, а не VS2022? На что это влияет? Live Object-ы мы победили все, за исключением annotation-а. Почему-то на него 2 ссылки ![image](https://user-images.githubusercontent.com/48070175/154581653-5129d358-0d3a-4097-bb9d-ed966afcd97c.png)

А, вы коварно подкинули fx файлы к исполняемому файлу =). Ну, тогда нужно к настройкам проекта добавить это копирование в post build step, а то у меня они все равно не появились, где нужно. Или проcто забыли vcxproj отдать?

2022-02-18 10:54 UTC, slmtnm commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
@anthark оставили только проверку после последнего релиза (девайса)

2022-02-18 11:10 UTC, kystyn commented on graphics.cpp
> +    hr = graphics->context->QueryInterface(__uuidof(graphics->annotation),
Спасибо за пояснения, теперь всё понятно)

2022-02-18 11:46 UTC, slmtnm commented
@anthark Добавили шейдеры в проект

2022-02-18 11:50 UTC, merged